### ISSUE TITLE
When cookie is set, values are added only by using the src parameter

### ISSUE THREAD

**Issue by bobbylechuga** [dm-guy/utm-alternative#7] opened 2015-10-22 14:48 UTC
Regards. This time I have a particular issue. I find that when there is already a path, the library is not able to save or organic search or the referral. However, if the cookie is empty, saving the organic search ...

The tests are running in: http://www.mentalidadweb.cl/

**Comment by dm-guy** [comment] 2015-10-23 12:13
Hi, could you please clarify so I can address your issue: 
"when there is already a path" - what do you mean by this? There is already a value in the cookie?
"However, if the cookie is empty, saving the organic search " - what do you mean?

**Comment by bobbylechuga** [comment] 2015-10-23 12:49
Hi, thanks for responding. Yes, keep me only organic source (eg "Googlg search") if I am entering for the first time on the website. Instead, if I enter the web site url first http://www.mentalidadweb.cl/google-analytics/?src=fb/social or link, and then return to enter a search in google, will not write more than ever in the cookie "google search".

**Comment by dm-guy** [comment] 2015-10-23 19:56
OK, I understand now. 
This is like this by design. It keeps the first traffic source that brought the user to the site. This way you can attribute conversion to the original source, rather than to the "last touch", which was the practice of Google Analytics (while they allow you to see the assisted conversions, you could see it only in an aggregated view on your dashboard and couldn't retrieve it through the UTM cookie).

At the same time, the plugin gives you flexibility by allowing you to add "src" to record in the cookie how you brought your users to your site deliberately (by remarketing, other campaigns and etc.).

However the use case you describe can be considered for the plugin. It just means that every time the user will google your site name or arrive through a referral, you will see "Google Search" or another referral in the cookie. This can bring a lot of data to the cookie. I am not sure users will find it handy. But I will chew on it a bit.

**Comment by pablogonzalezmw** [comment] 2015-10-23 20:28
Hi dm-guy.
The problem we are getting it the following. If the cookie does not exist, referral and organic source write perfectly the cookie.
But, if the cookie has a previous path, the organic and/or referral source don't write the cookie. That is what we mean.
I suppose that the design it is very useful to tag paid efforts, but if the user finally reached a convertion by Organic and/or referral, I think it is very important to get know it and send this value to the CRM. Currently, that is not happen, then we have no all the information to analize the journey until the convertion in CRM.
With campaign src source, the cookies write every path or interaction very well.
Thanks for your time! Please, chew on it a bit. :)
Best from Chile.

**Comment by dm-guy** [comment] 2015-10-24 15:29
Thanks for elaborating. This change is something I can add to the plugin in the near future, however it requires some more fixes as the change in logic require more changes. I'll probably release it as a new version, but not sure when that will be. I will close the issue for now.
Until then, enjoy the wines of Maipo :)

**Closed by dm-guy** 2015-10-24 15:29 UTC

**Comment by svensson-david** [comment] 2015-11-19 18:46
I was looking for similar functionality as the one requested above and did some alterations in the code. Let me know if you want me to post it somewhere.

**Comment by dm-guy** [comment] 2015-11-20 12:24
Hi David, it would be a great contribution if you could share it. I do not know how much changes you made, but you can either commit it, add it as a new version (2.0), or have your own if it's completely different. Looking forward!

**Comment by bobbylechuga** [comment] 2015-11-20 13:27
Hi guys, I also made some changes in the script to keep recurrence in writing cookie, I share here: 

```javascript
var traffic_source = "";
    var traffic_organic = ""; 
    if(document.cookie.indexOf(cookieName) === -1) {
        var traffic_source ="";
        setCookie(cookieName, traffic_source);
    }

    var urlParamSRC = getURLParameter("src"); //take the SRC value
    var referrerHostName = removeProtocol(document.referrer);
    if(urlParamSRC) {  
        traffic_source = urlParamSRC;        
    }else if (!urlParamSRC && referrerHostName === "") {
        //console.log("directo");
        traffic_source = "direct/none";
    }else if (!urlParamSRC && referrerHostName !== "") {
        //console.log ("referral"); 
        if (referrerHostName.indexOf('mentalidadweb.')  >= 0) {
            traffic_source = "";
        } else if (referrerHostName.indexOf('google.')  >= 0) {            
            traffic_source = "google/organic";
        } else if (referrerHostName.indexOf('bing.')  >= 0) {            
            traffic_source = "bing/organic";
        } else if (referrerHostName.indexOf('yahoo.')  >= 0) {            
            traffic_source = "yahoo/organic";
        } else {
            console.log ("Referral");
            traffic_source = referrerHostName;
        } 

    }
    if (traffic_source) {
        newTrafficSourceCookie = traffic_source + "|" + getCookie(cookieName);
        setCookie(cookieName, newTrafficSourceCookie);
    }
```

**Comment by svensson-david** [comment] 2015-11-20 13:51
I put my version in a gist: https://gist.github.com/svensson-david/ec8305a9a89d4a50f7cd
It has the same structure as the original one but I changed it to make sure each interaction is recorded as long as it's not a duplicate of the latest one. Internal links are not recorded.

I also changed the recorded data a bit, for referrals it will say:
referral>[SITE URL]
I use the same structure in the src-query, usually something like
?src=adwords>[CAMPAIGN NAME] or ?src=remarketing>[CAMPAIGN NAME]

Let me know if you want me to publish it in some other way, a pull request, a new version or similar.

**Comment by bobbylechuga** [comment] 2015-11-20 13:56
:) I'll check. After several successful tests, I created this fork with the changes. https://github.com/bobbylechuga/utm-alternative

**Comment by dm-guy** [comment] 2016-01-16 09:16
Hi, just to ping you guys that I appreciate your contribution and unfortunately I still haven't find the time to review it all. I do have some suggestions and changes and I will follow up soon I hope to discuss it with you. Cheers!

**Comment by dm-guy** [comment] 2016-08-17 12:48
Hi David, Bobby, 
I know it was long long time ago, but only now I found the time to work on it. 
I did a rewrite of the code based on the logic you suggested and the needs that you put forth. 
Most important thing is that the code is much cleaner. 
I was wondering, are you willing and have the time to test it as well? Please let me know.

**Comment by dm-guy** [comment] 2016-08-19 09:39
Hi, I released the new release, with a thank you note for both of you at the bottom of the main page. Thanks, and would be great if you could take a look as well.
